# Generated by Django 6.0 on 2026-01-23 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=63, unique=True)),
                ('title', models.CharField(max_length=127)),
                ('description', models.TextField()),
                ('crime_level', models.IntegerField(choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3')], default=3)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('AWAITING_TRIAL', 'Awaiting Trial'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='PENDING', max_length=31)),
                ('reported_at', models.DateTimeField(help_text='When the crime was reported')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=511, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Primary officer/detective assigned to this case', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Case',
                'verbose_name_plural': 'Cases',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CrimeScene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=511)),
                ('description', models.TextField()),
                ('occurred_at', models.DateTimeField(help_text='When the crime occurred')),
                ('discovered_at', models.DateTimeField(help_text='When the crime scene was discovered')),
                ('weather_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('lighting_conditions', models.CharField(blank=True, max_length=255, null=True)),
                ('scene_sketch', models.ImageField(blank=True, null=True, upload_to='crime_scenes/sketches/')),
                ('scene_photos', models.JSONField(default=list, help_text='List of photo file paths')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crime_scene', to='core.case')),
                ('discovered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_scenes', to=settings.AUTH_USER_MODEL)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_scenes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Crime Scene',
                'verbose_name_plural': 'Crime Scenes',
                'ordering': ['-created_at'],
            },
        ),
    ]
