# Generated by Django 5.0.3 on 2026-02-20 17:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='crimescene',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='crimescene',
            name='witnesses_info',
            field=models.JSONField(default=list, help_text="List of witnesses: {'name': '', 'phone': '', 'national_id': ''}"),
        ),
        migrations.AlterField(
            model_name='case',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='case',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='case',
            name='reported_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crimescene',
            name='discovered_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crimescene',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='crimescene',
            name='occurred_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='crimescene',
            name='scene_photos',
            field=models.JSONField(default=list),
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('RETURNED', 'Returned for Correction'), ('SENT_TO_OFFICER', 'Sent to Officer'), ('VOID', 'Voided (3 Strikes)'), ('APPROVED', 'Converted to Case')], default='PENDING', max_length=31)),
                ('rejection_count', models.PositiveIntegerField(default=0, help_text='Count of returns for corrections. Max is 3.')),
                ('trainee_feedback', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_complaints', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
