# Generated by Django 5.0.3 on 2026-02-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_case_options_alter_crimescene_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Requires approval from a higher rank unless created by Chief.'),
        ),
    ]
