# Generated by Django 5.0.3 on 2026-02-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_case_is_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='plaintiffs_info',
            field=models.JSONField(blank=True, default=list, help_text="List of plaintiffs: [{'name': '', 'phone': '', 'national_id': ''}]"),
        ),
    ]
