# Generated by Django 6.0 on 2026-01-23 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WitnessStatement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('witness_name', models.CharField(max_length=127)),
                ('witness_phone', models.CharField(blank=True, max_length=31, null=True)),
                ('witness_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('witness_address', models.TextField(blank=True, null=True)),
                ('witness_id_number', models.CharField(blank=True, max_length=127, null=True)),
                ('witness_age', models.IntegerField(blank=True, null=True)),
                ('statement', models.TextField(help_text="Witness's statement about the incident")),
                ('statement_date', models.DateTimeField()),
                ('statement_location', models.CharField(blank=True, max_length=511, null=True)),
                ('relationship_to_case', models.CharField(blank=True, help_text='How the witness is related to the case (victim, bystander, etc.)', max_length=127, null=True)),
                ('is_confidential', models.BooleanField(default=False, help_text='Whether this witness statement should be kept confidential')),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_notes', models.TextField(blank=True, null=True)),
                ('statement_recording', models.FileField(blank=True, null=True, upload_to='witness_statements/recordings/')),
                ('statement_transcript', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='witness_statements', to='core.case')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_statements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Witness Statement',
                'verbose_name_plural': 'Witness Statements',
                'ordering': ['-statement_date'],
            },
        ),
    ]
