# Generated by Django 5.0.3 on 2026-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('witnesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='witnessstatement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
