# Generated by Django 5.0.3 on 2026-02-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badge_number',
            field=models.CharField(blank=True, help_text='Police badge number (Only for police personnel)', max_length=63, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CITIZEN', 'Citizen'), ('TRAINEE', 'Trainee'), ('MEDICAL_EXAMINER', 'Medical Examiner'), ('POLICE_OFFICER', 'Police Officer'), ('PATROL_OFFICER', 'Patrol Officer'), ('DETECTIVE', 'Detective'), ('SERGEANT', 'Sergeant'), ('CAPTAIN', 'Captain'), ('POLICE_CHIEF', 'Police Chief')], default='CITIZEN', help_text="User's role/rank in the department or citizen status", max_length=31),
        ),
    ]
