# Generated by Django 6.0 on 2026-01-23 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reward_type', models.CharField(choices=[('CASE_SOLVED', 'Case Solved'), ('EXCELLENT_INVESTIGATION', 'Excellent Investigation'), ('SUSPECT_ARRESTED', 'Suspect Arrested'), ('EVIDENCE_COLLECTED', 'Key Evidence Collected'), ('OTHER', 'Other')], max_length=31)),
                ('description', models.TextField(help_text='Reason for the reward')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Reward amount', max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=127, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['CAPTAIN', 'POLICE_CHIEF']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_rewards', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to='core.case')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reward',
                'verbose_name_plural': 'Rewards',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(max_length=127, unique=True)),
                ('payment_type', models.CharField(choices=[('BAIL', 'Bail Payment'), ('FINE', 'Fine Payment'), ('REWARD', 'Reward Payment'), ('OTHER', 'Other')], max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=15)),
                ('payer_name', models.CharField(max_length=127)),
                ('payer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('payer_phone', models.CharField(blank=True, max_length=31, null=True)),
                ('payment_method', models.CharField(blank=True, help_text='Payment gateway used (Zarinpal, IDPay, etc.)', max_length=31, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=127, null=True)),
                ('payment_reference', models.CharField(blank=True, max_length=127, null=True)),
                ('initiated_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.case')),
                ('reward', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment', to='rewards.reward')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
