# Generated by Django 5.0.3 on 2026-02-26 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_alter_payment_id_alter_reward_id'),
        ('suspects', '0003_interrogation_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='suspect',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='suspects.suspect'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_reference',
            field=models.CharField(blank=True, help_text='Gateway authority or reference code', max_length=127, null=True),
        ),
    ]
