# Generated by Django 6.0 on 2026-01-23 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('national_id', models.CharField(blank=True, max_length=31, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=31, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=15, null=True)),
                ('weight', models.CharField(blank=True, max_length=15, null=True)),
                ('eye_color', models.CharField(blank=True, max_length=31, null=True)),
                ('hair_color', models.CharField(blank=True, max_length=31, null=True)),
                ('distinguishing_marks', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='suspects/photos/')),
                ('status', models.CharField(choices=[('IDENTIFIED', 'Identified'), ('UNDER_INVESTIGATION', 'Under Investigation'), ('INTERROGATED', 'Interrogated'), ('CHARGED', 'Charged'), ('AWAITING_TRIAL', 'Awaiting Trial'), ('IN_CUSTODY', 'In Custody'), ('RELEASED', 'Released'), ('CLEARED', 'Cleared')], default='IDENTIFIED', max_length=31)),
                ('identified_at', models.DateTimeField(blank=True, null=True)),
                ('interrogation_date', models.DateTimeField(blank=True, null=True)),
                ('interrogation_notes', models.TextField(blank=True, null=True)),
                ('interrogation_recording', models.FileField(blank=True, null=True, upload_to='suspects/interrogations/')),
                ('charges', models.TextField(blank=True, help_text='Charges filed against the suspect', null=True)),
                ('charged_date', models.DateTimeField(blank=True, null=True)),
                ('arrest_date', models.DateTimeField(blank=True, null=True)),
                ('release_date', models.DateTimeField(blank=True, null=True)),
                ('bail_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('bail_paid', models.BooleanField(default=False)),
                ('prior_convictions', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suspects', to='core.case')),
                ('identified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='identified_suspects', to=settings.AUTH_USER_MODEL)),
                ('interrogated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interrogated_suspects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Suspect',
                'verbose_name_plural': 'Suspects',
                'ordering': ['-created_at'],
            },
        ),
    ]
