# Generated by Django 6.0 on 2026-01-23 19:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('suspects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trial_number', models.CharField(max_length=127, unique=True)),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress'), ('ADJOURNED', 'Adjourned'), ('COMPLETED', 'Completed'), ('DISMISSED', 'Dismissed'), ('POSTPONED', 'Postponed')], default='SCHEDULED', max_length=15)),
                ('scheduled_date', models.DateTimeField()),
                ('started_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('court_name', models.CharField(max_length=127)),
                ('court_location', models.CharField(blank=True, max_length=255, null=True)),
                ('judge_name', models.CharField(blank=True, max_length=127, null=True)),
                ('prosecutor_name', models.CharField(blank=True, max_length=127, null=True)),
                ('defense_attorney_name', models.CharField(blank=True, max_length=127, null=True)),
                ('verdict', models.CharField(blank=True, choices=[('GUILTY', 'Guilty'), ('NOT_GUILTY', 'Not Guilty'), ('PENDING', 'Pending'), ('MISTRIAL', 'Mistrial')], max_length=15, null=True)),
                ('sentence', models.TextField(blank=True, null=True)),
                ('fine_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fine_paid', models.BooleanField(default=False)),
                ('trial_notes', models.TextField(blank=True, null=True)),
                ('case_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attended_by', models.ManyToManyField(blank=True, help_text='Police officers who attended the trial', related_name='attended_trials', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='core.case')),
                ('suspect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trials', to='suspects.suspect')),
            ],
            options={
                'verbose_name': 'Trial',
                'verbose_name_plural': 'Trials',
                'ordering': ['-scheduled_date'],
            },
        ),
    ]
