# Generated by Django 6.0 on 2026-01-23 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_number', models.CharField(max_length=127, unique=True)),
                ('evidence_type', models.CharField(choices=[('BIOLOGICAL', 'Biological Evidence'), ('MEDICAL', 'Medical Evidence'), ('VEHICLE', 'Vehicle Evidence'), ('IDENTIFICATION', 'Identification Documents'), ('DOCUMENT', 'Document Evidence'), ('PHOTOGRAPH', 'Photograph'), ('VIDEO', 'Video Recording'), ('AUDIO', 'Audio Recording'), ('FINGERPRINT', 'Fingerprint'), ('DNA', 'DNA Sample'), ('WEAPON', 'Weapon'), ('OTHER', 'Other')], max_length=31)),
                ('description', models.TextField()),
                ('location_found', models.CharField(blank=True, max_length=511, null=True)),
                ('collected_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('COLLECTED', 'Collected'), ('IN_ANALYSIS', 'In Analysis'), ('ANALYZED', 'Analyzed'), ('STORED', 'Stored'), ('DISPOSED', 'Disposed')], default='COLLECTED', max_length=31)),
                ('photos', models.JSONField(default=list, help_text='List of photo file paths')),
                ('documents', models.JSONField(default=list, help_text='List of document file paths')),
                ('storage_location', models.CharField(blank=True, max_length=255, null=True)),
                ('chain_of_custody', models.JSONField(default=list, help_text='List of custody transfers with timestamps and officers')),
                ('analysis_results', models.TextField(blank=True, null=True)),
                ('analysis_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('analyzed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyzed_evidence', to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='core.case')),
                ('collected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evidence',
                'verbose_name_plural': 'Evidence',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BiologicalEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('sample_type', models.CharField(max_length=127)),
                ('lab_reference_number', models.CharField(blank=True, max_length=127, null=True)),
            ],
            options={
                'verbose_name': 'Biological Evidence',
                'verbose_name_plural': 'Biological Evidence',
            },
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='IdentificationEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('document_type', models.CharField(max_length=127)),
                ('document_number', models.CharField(blank=True, max_length=127, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=127, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Identification Evidence',
                'verbose_name_plural': 'Identification Evidence',
            },
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='VehicleEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('vehicle_license_plate', models.CharField(blank=True, max_length=63, null=True)),
                ('vehicle_make', models.CharField(blank=True, max_length=127, null=True)),
                ('vehicle_model', models.CharField(blank=True, max_length=127, null=True)),
                ('vehicle_color', models.CharField(blank=True, max_length=31, null=True)),
                ('vin_number', models.CharField(blank=True, max_length=63, null=True)),
            ],
            options={
                'verbose_name': 'Vehicle Evidence',
                'verbose_name_plural': 'Vehicle Evidence',
            },
            bases=('evidence.evidence',),
        ),
        migrations.CreateModel(
            name='MedicalEvidence',
            fields=[
                ('evidence_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='evidence.evidence')),
                ('examination_date', models.DateTimeField(blank=True, null=True)),
                ('medical_report', models.TextField(blank=True, null=True)),
                ('examiner', models.ForeignKey(blank=True, limit_choices_to={'role': 'MEDICAL_EXAMINER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_examinations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Evidence',
                'verbose_name_plural': 'Medical Evidence',
            },
            bases=('evidence.evidence',),
        ),
    ]
