# Generated by Django 5.0.3 on 2026-02-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0002_alter_evidence_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='identificationevidence',
            name='extra_details',
            field=models.JSONField(blank=True, default=dict, help_text='Custom key-value pairs for specific document information'),
        ),
    ]
